default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  username: hotspot
  password: 123456
  database: hotspot_development

test:
  <<: *default
  database: hotspot_test

staging:
  <<: *default
  database: hotspot_staging
  username: postgres
  password: <%= ENV['HOTSPOT_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: hotspot_production
  username: hotspot
  password: 123456
