default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: hotspot_development

test:
  <<: *default
  database: hotspot_test

staging:
  <<: *default
  database: hotspot_staging
  username: postgres
  password: <%= Figaro.env.database_password %>

production:
  <<: *default
  database: hotspot_production
  username: postgres
  password: <%= Figaro.env.database_password %>
