default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: hotspot_development

test:
  <<: *default
  database: hotspot_test

staging:
  <<: *default
  database: hotspot_staging

production:
  <<: *default
  host: <%= ENV["POSTGRES_HOST"] %>
  database: hotspot_production
